/* ============================================================
   LUXIGA CRM — branded email templates (runtime source of truth)
   ============================================================

   Email-client-safe HTML: table-based layout, inline styles, web-safe
   font stack (Space Grotesk with Arial/Helvetica fallbacks). Renders
   correctly in Gmail, Apple Mail, and Outlook.

   These are the templates the Worker actually sends. The static files in
   ../email-templates/*.html are design-review previews of the same markup,
   regenerated by ../email-templates/build_emails.py — keep the two in step.

   Brand: dark #080810 header band, "LUXIGA" wordmark in lime #C4FF53,
   near-white body on a light page for readability, lime accent buttons.
*/

export const BRAND = {
  bg:      '#e9ecdf',   // page background (light)
  card:    '#ffffff',
  head:    '#080810',   // dark header/footer band
  lime:    '#C4FF53',
  limeInk: '#0a0a0a',   // text on lime
  ink:     '#16161d',
  soft:    '#44483d',
  muted:   '#8b917d',
  headMuted: '#8f9a78', // muted text on the dark band
  link:    '#4f6b16',   // dark-lime, readable on white
  line:    '#e4e7dc',
  panel:   '#f5f7ee',
  site:    'https://luxiga.co',
  wordmark: 'LUXIGA',
  tagline:  'Product Design · Software',
  founder:  'Lukas Green',
  company:  'LUXIGA LLC',
  phone:    '503-427-8497',
  emailAddr: 'lukas@lukasdgreen.com',
  adminUrl: 'https://luxiga.co/admin.html',
};

const FONT = "'Space Grotesk',-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,Helvetica,sans-serif";

export function escapeHtml(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

// Newline-preserving escape for free-text (messages).
function escapeMultiline(s) {
  return escapeHtml(s).replace(/\n/g, '<br>');
}

// ---------------------------------------------------------------- row helpers
// Each returns a <tr> so callers compose an email body by concatenating rows.

export function pRow(html) {
  return `<tr><td style="padding:0 32px 16px;font:400 16px/1.62 ${FONT};color:${BRAND.ink}">${html}</td></tr>`;
}

export function hRow(text) {
  return `<tr><td style="padding:8px 32px 8px;font:700 17px ${FONT};color:${BRAND.ink}">${escapeHtml(text)}</td></tr>`;
}

// A bordered key/value panel. pairs = [[label, value], ...] (values pre-escaped or plain).
export function panelRow(pairs) {
  const rows = pairs.map(([label, value]) => (
    `<tr>` +
    `<td valign="top" style="padding:5px 14px 5px 0;font:600 13px ${FONT};color:${BRAND.muted};white-space:nowrap">${escapeHtml(label)}</td>` +
    `<td style="padding:5px 0;font:400 15px/1.5 ${FONT};color:${BRAND.ink}">${value}</td>` +
    `</tr>`
  )).join('');
  return `<tr><td style="padding:2px 32px 16px">` +
    `<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:${BRAND.panel};border:1px solid ${BRAND.line};border-radius:12px">` +
    `<tr><td style="padding:14px 18px"><table role="presentation" cellpadding="0" cellspacing="0" width="100%">${rows}</table></td></tr>` +
    `</table></td></tr>`;
}

// A quoted free-text block (the requester's message).
export function quoteRow(text) {
  return `<tr><td style="padding:2px 32px 16px">` +
    `<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-left:3px solid ${BRAND.lime};background:${BRAND.panel};border-radius:0 10px 10px 0">` +
    `<tr><td style="padding:14px 18px;font:400 15px/1.6 ${FONT};color:${BRAND.soft}">${escapeMultiline(text)}</td></tr>` +
    `</table></td></tr>`;
}

export function stepsRow(items) {
  const rows = items.map((it, i) => (
    `<tr>` +
    `<td valign="top" style="padding:0 12px 12px 0;width:30px">` +
    `<div style="width:26px;height:26px;border-radius:50%;background:${BRAND.lime};color:${BRAND.limeInk};font:700 14px ${FONT};text-align:center;line-height:26px">${i + 1}</div></td>` +
    `<td style="padding:0 0 12px;font:400 15px/1.55 ${FONT};color:${BRAND.soft}">${it}</td>` +
    `</tr>`
  )).join('');
  return `<tr><td style="padding:2px 32px 8px"><table role="presentation" cellpadding="0" cellspacing="0" width="100%">${rows}</table></td></tr>`;
}

export function ctaRow(text, href) {
  return `<tr><td style="padding:10px 32px 22px">` +
    `<a href="${href}" style="display:inline-block;background:${BRAND.lime};color:${BRAND.limeInk};font:700 16px ${FONT};text-decoration:none;padding:14px 26px;border-radius:10px">${escapeHtml(text)}</a>` +
    `</td></tr>`;
}

export function signRow(lines) {
  const body = lines.map(escapeHtml).join('<br>');
  return `<tr><td style="padding:8px 32px 6px;font:400 15px/1.6 ${FONT};color:${BRAND.soft}">${body}</td></tr>`;
}

// ---------------------------------------------------------------- layout
// Full document. `inner` is the concatenated body rows; `footerExtraHtml` is
// injected into the footer band (e.g. the unsubscribe line for campaigns).
export function wrap({ title, preheader, inner, footerExtraHtml = '' }) {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting"><title>${escapeHtml(title)}</title>
<style>
  body{margin:0;padding:0;background:${BRAND.bg}}
  a{color:${BRAND.link}}
  @media (max-width:600px){ .card{width:100%!important} .px{padding-left:20px!important;padding-right:20px!important} }
</style></head>
<body style="margin:0;padding:0;background:${BRAND.bg};-webkit-text-size-adjust:100%;">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:${BRAND.bg};font-size:1px;line-height:1px">${escapeHtml(preheader || '')}</div>
  <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:${BRAND.bg}">
   <tr><td align="center" style="padding:26px 12px 34px">
    <table role="presentation" class="card" cellpadding="0" cellspacing="0" width="600" style="width:600px;max-width:600px;background:${BRAND.card};border-radius:16px;overflow:hidden;border:1px solid ${BRAND.line}">
      <!-- header -->
      <tr><td style="background:${BRAND.head};padding:24px 32px" align="center">
        <div style="font:700 22px ${FONT};letter-spacing:4px;color:${BRAND.lime}">${BRAND.wordmark}</div>
        <div style="font:600 10px ${FONT};letter-spacing:3px;color:${BRAND.headMuted};padding-top:5px;text-transform:uppercase">${escapeHtml(BRAND.tagline)}</div>
      </td></tr>
      <tr><td style="height:24px"></td></tr>
      ${inner}
      <tr><td style="height:12px"></td></tr>
      <!-- footer -->
      <tr><td style="background:${BRAND.head};padding:20px 32px" align="center">
        <div style="font:700 13px ${FONT};letter-spacing:2px;color:${BRAND.lime}">${BRAND.wordmark}</div>
        <div style="font:400 12px/1.7 ${FONT};color:${BRAND.headMuted};padding-top:6px">
          ${escapeHtml(BRAND.company)} &middot; <a href="${BRAND.site}" style="color:${BRAND.lime};text-decoration:none">luxiga.co</a><br>
          <a href="tel:+15034278497" style="color:${BRAND.headMuted};text-decoration:none">${escapeHtml(BRAND.phone)}</a> &middot;
          <a href="mailto:${BRAND.emailAddr}" style="color:${BRAND.headMuted};text-decoration:none">${escapeHtml(BRAND.emailAddr)}</a>
        </div>
        ${footerExtraHtml}
      </td></tr>
    </table>
   </td></tr>
  </table>
</body></html>`;
}

// ---------------------------------------------------------------- templates

// To Lukas when someone submits the business-card work-request form.
export function workRequestNotifyHtml(d) {
  const name = d.name || '(no name)';
  const inner = [
    pRow(`<b>New work request</b> just came in through the card.`),
    panelRow([
      ['Name', escapeHtml(name)],
      ['Email', d.email ? `<a href="mailto:${escapeHtml(d.email)}">${escapeHtml(d.email)}</a>` : '(not provided)'],
      ['Phone', d.phone ? escapeHtml(d.phone) : '(not provided)'],
      ['Source', escapeHtml(d.source || 'Card Scan')],
      ['When', escapeHtml(d.when || new Date().toISOString())],
    ]),
    hRow('What they need'),
    quoteRow(d.message || '(no message)'),
    ctaRow('Open the CRM', BRAND.adminUrl),
    d.email ? pRow(`<span style="color:${BRAND.muted};font-size:14px">Reply to this email to respond to ${escapeHtml(name)} directly.</span>`) : '',
  ].join('');
  return wrap({
    title: `New work request — ${name}`,
    preheader: `${name} wants to talk about a project.`,
    inner,
  });
}

// Auto-reply to the person who submitted the work-request form.
export function workRequestReceiptHtml(d) {
  const name = d.name || 'there';
  const inner = [
    pRow(`Hi ${escapeHtml(name)},`),
    pRow(`Thanks for reaching out. I got your note and I'll be in touch shortly — usually within a day.`),
    hRow('What happens next'),
    stepsRow([
      `<b>I read it personally.</b> Your request comes straight to me, not a queue.`,
      `<b>We talk.</b> A quick call or email to understand what you're building and whether I'm the right fit.`,
      `<b>A clear plan.</b> If it's a match, you get a scoped approach and next steps — no pressure.`,
    ]),
    pRow(`In the meantime, feel free to just reply to this email if anything comes up.`),
    signRow(['Talk soon,', `${BRAND.founder}`, `Founder, ${BRAND.company}`, 'luxiga.co']),
  ].join('');
  return wrap({
    title: 'Got your request — LUXIGA',
    preheader: `Thanks ${name} — I got your note and I'll be in touch shortly.`,
    inner,
  });
}

// Weekly digest / follow-up nudge to Lukas. `rows` = panel pairs; `listHtml`
// = optional pre-built HTML block (e.g. the contact list).
export function internalDigestHtml({ title, preheader, headline, statPairs = [], sections = [] }) {
  const parts = [pRow(`<b>${escapeHtml(headline)}</b>`)];
  if (statPairs.length) parts.push(panelRow(statPairs));
  for (const s of sections) {
    parts.push(hRow(s.heading));
    parts.push(`<tr><td style="padding:0 32px 16px;font:400 14px/1.6 ${FONT};color:${BRAND.soft}">${s.html}</td></tr>`);
  }
  parts.push(ctaRow('Open the CRM', BRAND.adminUrl));
  return wrap({ title, preheader, inner: parts.join('') });
}

// The wrapper marketing campaigns render into (the resend provider path).
// `bodyHtml` is the admin-authored campaign body (already HTML). `unsubUrl`
// is the signed one-click link; `postal` satisfies CAN-SPAM.
export function campaignBaseHtml({ subject, preview, bodyHtml, unsubUrl, postal }) {
  const inner = `<tr><td style="padding:0 32px 8px;font:400 16px/1.62 ${FONT};color:${BRAND.ink}">${bodyHtml}</td></tr>`;
  const footerExtraHtml =
    `<div style="font:400 11px/1.6 ${FONT};color:#6a6f5e;padding-top:12px">` +
    `${escapeHtml(postal || `${BRAND.company}`)}<br>` +
    `You're receiving this because you connected with ${escapeHtml(BRAND.company)}.<br>` +
    `<a href="${unsubUrl}" style="color:${BRAND.headMuted};text-decoration:underline">Unsubscribe</a> from these emails.` +
    `</div>`;
  return wrap({
    title: subject || 'LUXIGA',
    preheader: preview || '',
    inner,
    footerExtraHtml,
  });
}

// Public confirmation page shown after a one-click unsubscribe.
export function unsubPageHtml(email, ok) {
  const safe = escapeHtml(email || '');
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Unsubscribed — LUXIGA</title>
<style>
  body{font-family:${FONT};background:${BRAND.head};color:#f0f1ea;max-width:520px;margin:0 auto;padding:14vh 22px;text-align:center}
  .mark{font-weight:700;letter-spacing:4px;color:${BRAND.lime};font-size:20px;margin-bottom:26px}
  h1{font-size:1.35rem;margin:0 0 12px}
  .ok{color:${BRAND.lime}} .err{color:#ff8a8a}
  p{color:#b7bda8;line-height:1.6} a{color:${BRAND.lime}}
  .foot{margin-top:2.4rem;font-size:.8rem;color:#6a6f5e}
</style></head><body>
<div class="mark">LUXIGA</div>
${ok
  ? `<h1 class="ok">You're unsubscribed</h1><p><strong>${safe}</strong> won't receive any more marketing emails from LUXIGA.</p>`
  : `<h1 class="err">Link expired or invalid</h1><p>We couldn't process that unsubscribe link. Email us and we'll remove you right away.</p>`}
<div class="foot">${escapeHtml(BRAND.company)} &middot; <a href="${BRAND.site}">luxiga.co</a></div>
</body></html>`;
}
